### ISSUE TITLE
url, TEL, FAX項目名変更対応

### ISSUE THREAD

**Issue by ymits** [codeforchiba/papamama#105]

**Comment by snakamu** [comment]
@iMitsugu @ymits 
データ項目名が、```TEL, FAX → Tel,Fax```に変更になりましたが、
マップ上でのTEL, FAXの表示も、あわせて変えた方がよろしいでしょうか？

**Comment by iMitsugu** [comment]
いいえ。変更したのはデータ項目としてであって、表記上は今までと変更なしでお願いいたします。

**Comment by snakamu** [comment]
@iMitsugu ありがとうございます。表示上はそのままで対応いたします。

**Comment by ymits** [comment]
対応完了
