### ISSUE TITLE
日付のフォーマットをYYYYMMDD想定にする

### ISSUE THREAD

**Issue by ymits** [codeforchiba/papamama#13]
現在もらっているデータはExcelのシリアル値になっているが
YYYYMMDDの文字列形式にしてもらう対応

**Comment by iMitsugu** [comment]
千葉市から、上記のとおり文字列形式にする旨、承諾をいただきました。
VacancyDateについては、データには入っていませんが、評議会版にあるため影響はないでしょうか？

**Comment by ymits** [comment]
データの最新化にあわせて対応
