### ISSUE TITLE
お気に入り一覧からお気に入りを削除できるようにする

### ISSUE THREAD

**Issue by ymits** [codeforchiba/papamama#14]
お気に入り一覧画面からお気に入りを削除できた方が使い勝手がいい！

**Comment by snakamu** [comment]
削除後の一覧の更新に関して、
画面をreloadしていたが、一覧部分のみの更新に変更しました。
(reloadだと、他画面遷移時にtitleが変わらない問題があった。)

**Comment by ymits** [comment]
こちらの機能ですがβ版リリースに向けてreload状態のままマージしました。
大変だったとは思いますが、調査＆対応ありがとうございました。

検討中だったreloadを外す対応は本リリースには含めたいと思いますので継続調査お願いします。

**Comment by snakamu** [comment]
承知しました。
現在の調査結果として、地図上をクリックした時に呼ばれる以下の処理のcoord(緯度,経度)部分に、
緯度経度を意図的に設定してやると設定場所まで動き地図上が更新されます。

> papamamap.animatedMove(coord[0], coord[1], false);

固定値を決めてやれれば使えそうです。すでにあるinit_center_coordsではダメそうです。

> var init_center_coords = [140.1112972, 35.6129448];

よろしくお願いします。

**Comment by snakamu** [comment]
調査追記

> map = papamamap.map;
> map.getView().getCenter();

で現在の中心座標が取得できるので、
初回表示時と地図上クリック時に、中心座標を取得保存する処理を追記。
削除があった場合は、地図画面に戻った際、保存した中心座標に移動し、地図上が自動更新されるという方法があります。
reloadよりはまだ良いでしょうか。
よろしくお願いします。

**Comment by ymits** [comment]
色々調査ありがとうございます。

１点どうしてもきになることがあります。

> papamamap.updateNurseryStyle(feature);

こちらでなぜスタイルが更新されないかわかりますか？

園の詳細ダイアログからはこちらのapiを読んでスタイル更新できて、
お気に入り一覧からこちらのapiを読んでもスタイル更新できない理由が気になります。

違いは何か？この辺調査してもらってもいいですか？

**Comment by snakamu** [comment]
調査追記

> papamamap.updateNurseryStyle(feature);

のfeatureは、クリック位置の施設情報取得時に実行している、
OpenLayersのforEachFeatureAtPixel処理を利用し生成しております。

> obj = map.forEachFeatureAtPixel( 〜 );
> feature = obj.feature;

この方法でfeatureを生成しないと、updateNurseryStyle使えないように思われます。

**Comment by ymits** [comment]
なるほど。了解です。

このアプリ保育園情報をOpenLayersのオブジェクトで扱ってたりJSONデータそのまま扱ってたり、その辺なんか複雑ですよね。

自分の方でもupdateNurseryStyle確認しましたが渡したオブジェクトからType(認可、認可外、保育園)が取得できればOpenLayersのオブジェクトだろうがJSONオブジェクトだろうが関係ない気がします。

自分のローカルでupdateNurseryStyleをちょっと直してどちらのオブジェクトからでもTypeが取得できるようにして見たらうまく動いているようには見えます。

新しい仕組みを作るよりかはupdateNurseryStyleを修正して動くようにした方がシンプルでいいかと思います。updateNurseryStyleを修正する方針で問題ないか確認お願いしてもいいですか？

**Comment by snakamu** [comment]
ご助言ありがとうございます。
updateNurseryStyleで更新するように変更してみました。動作として問題ないと思われます。

ただ、修正中に気づいたのですが、お気に入り画面・比較画面でブラウザ更新すると、
メイン画面pageshow時に設定される保育施設情報が初期化されるため、以下の問題があります。
・お気に入り画面
　削除実行時、updateNurseryStyle内でエラーになり、削除できるが自動でメイン画面に移動する。
　(Cannot read property)
・比較画面
　比較表が空になる。

> メイン画面pageshowの設定処理
> // 地図レイヤー定義
>     papamamap.viewCenter = init_center_coords;
>     papamamap.generate(mapServerList['bing-road']);
>     map = papamamap.map;
>        // 保育施設の読み込みとレイヤーの追加
>     loadNurseryFacilitiesPromise.done(function(){
>         papamamap.addNurseryFacilitiesLayer(nurseryFacilities);
>     });

**Comment by ymits** [comment]
対応ありがとうございます。

> ただ、修正中に気づいたのですが、お気に入り画面・比較画面でブラウザ更新すると、
メイン画面pageshow時に設定される保育施設情報が初期化されるため、以下の問題があります。
・お気に入り画面
　削除実行時、updateNurseryStyle内でエラーになり、削除できるが自動でメイン画面に移動する。
　(Cannot read property)
・比較画面
　比較表が空になる。

この辺の問題はしょうがないですね。
この辺の問題を解消しようとすると作りを根本的に直す必要があり、今回はそこまでしなくてもいいかなと思っています。

こちらPRお願いします。

**Comment by snakamu** [comment]
ご確認ありがとうございます。PRします。

**Comment by ymits** [comment]
対応済み
