### ISSUE TITLE
FAXの表示がされない

### ISSUE THREAD

**Issue by ymits** [codeforchiba/papamama#33]
②と同様データが入っている場合でも表示がされておりませんでした。
　　これにつきましては、先日幼保運営課と打合せをした際、「問合せ用にFAXを使う保育所はない」とのことでしたので、表示されなくても問題ないのですが、
　　オープンソースとしてどこかの自治体が使う際には必要かと思いましたので、伝えさせていただきました。

**Comment by misopeso** [comment]
> オープンソースとしてどこかの自治体が使う際には必要かと思いましたので、伝えさせていただきました。

この意味だと、オープンガバメント推進協議会版に入れないと、意味ないかもと思えますなぁ。

**Comment by ymits** [comment]
PRマージした後にこのチケット確認したのでPRは既にマージしてしまっていますが、確かにオープンガバメント推進協議会版に入れないと、意味ないかもですね。

そちらにはどうやって修正すればいいんですかね？

**Comment by misopeso** [comment]
オープンガバメント推進協議会版については、PR は好きに送ってくれていい、という話はしてます。

でも、その後の運用は決まってないですね。こちらで、勝手にマージするわけにもいかないので。。。

**Comment by ymits** [comment]
本当に問題があれば再度チケット化されると思うので対応予定なしで一旦クローズします。
