### ISSUE TITLE
お気に入りボタンの位置について

### ISSUE THREAD

**Issue by ymits** [codeforchiba/papamama#34]
お気に入りボタンが一番上に表示されているのですが、スマホで使ってみますと、お気に入りを押そうとして、その付近にある別のボタンが押されてしまうことがあります。（保育所名称のリンクなど）
　　できれば最後の方にお気に入りボタンがあるといいのかなと思いましたが、いかがでしょうか？

**Comment by misopeso** [comment]
対応可否を検討する

**Comment by ymits** [comment]
対応予定なしでクローズ
