### ISSUE TITLE
IEだと比較結果が表示されない

### ISSUE THREAD

**Issue by ymits** [codeforchiba/papamama#35]
GoogleChromeだと比較結果が表示されるのですが、IEだと表示されませんでした。
　　どこまで対応させるべきかについてはCodeforChiba様のお考え次第と思っておりますが、IEを使っているユーザーも多いと思われますので、お伝えさせていただきました。

**Comment by snakamu** [comment]
IEで出る比較画面のエラーをのせておきます。

![ie](https://cloud.githubusercontent.com/assets/11253385/20864632/6ccdbafe-ba3c-11e6-9689-4e0252461159.png)

**Comment by ymits** [comment]
arrayのfindメソッドははes2016のドラフト実装なのでchromeとfirefoxしかまだ実装の対応されてないですね。

IEでも動くように作り直します。

**Comment by snakamu** [comment]
https://github.com/codeforchiba/papamama/pull/73 で対応済
