### ISSUE TITLE
地図上にノースアップを追加する

### ISSUE THREAD

**Issue by snakamu** [codeforchiba/papamama#38]
地図を回転することができるので、ノースアップを追加する

**Comment by snakamu** [comment]
openlayersのol.jsを解読する必要があり、時間かかりそうなので、後回しにします。

**Comment by iMitsugu** [comment]
この件は、
https://github.com/codeforchiba/papamama/pull/56
と同じイシューでしょうか？

**Comment by snakamu** [comment]
issue #38 のPull request(レビュー依頼)が、PR #56 になります。

**Comment by ymits** [comment]
対応済み
