### ISSUE TITLE
千葉市版の検索条件を見直す

### ISSUE THREAD

**Issue by ymits** [codeforchiba/papamama#4]
左上の施設（認可、認可外、幼）がベース
絞り込み検索は、これらの施設に関係なく一律メニュー
（現状は施設毎に絞り込みメニューが異なりわかりにくい）

**Comment by snakamu** [comment]
データについて質問なのですが、Close(閉園時間)に「翌」がつくのは夜中の何時からでしょうか。
今は、0時より後(0時01分でも)は翌がつく想定でロジックを組んでおります。
よろしくお願いします。

**Comment by iMitsugu** [comment]
ご指摘をありがとうございます。はい。そのようにいたします。既にデータとしてあるのは、
翌7:00、24:00がありますので、0:00～24:00はそのまま表記し、その後は1分過ぎたら「翌0:01」と表せばよいと思います。
