### ISSUE TITLE
検索時の幼稚園情報の表示が壊れている

### ISSUE THREAD

**Issue by snakamu** [codeforchiba/papamama#46]
絞り込み検索で、条件指定「24時間」をして、条件適用すると、幼稚園レイヤが消えます（認可、認可外はそのまま）。そしてその後、幼稚園レイヤのボタンを押下すると、検索条件とは関係なくすべての幼稚園POIが表示されてしまいます。
（幼稚園レイヤのみ挙動が異なります）

**Comment by snakamu** [comment]
幼稚園で、検索条件となりうる項目を教えて頂きたいです。
現在はこども園だけなっているようです。

**Comment by iMitsugu** [comment]
いくつか複合しているように見えますが、こちらは認可、認可外、幼稚園を全て出ている状態で、一時保育で絞込みを行うと、幼稚園のレイヤがOFFになる現象です。
仕様書がなくて恐縮ですが、一時保育の幼稚園がない場合は幼稚園のレイヤはそのまま残りPOIが出ない状態になるべきだと思います。

![chibapama1](https://cloud.githubusercontent.com/assets/23208846/20612067/22d7dece-b2f9-11e6-9bd6-cfa52c5d747c.png)
![chibapama2](https://cloud.githubusercontent.com/assets/23208846/20612068/24d426ec-b2f9-11e6-82c7-af31b482c762.png)
![chibapama3](https://cloud.githubusercontent.com/assets/23208846/20612071/26d3a422-b2f9-11e6-9d73-08e8360c4bef.png)

**Comment by iMitsugu** [comment]
その後、幼稚園レイヤをONにすると絞り込まれている状況ですが、幼稚園のPOIが全て出てしまいます。
![chibapama4](https://cloud.githubusercontent.com/assets/23208846/20612140/191c3604-b2fa-11e6-8add-dcf43dd2bb2d.png)

**Comment by snakamu** [comment]
・ソース上検索指定項目によりデータ内容に関わらずレイヤの選択・非選択がわかれております。例:保育ルーム認定は認定外しか選択されない。
こちら、レイヤはすべて選択統一にするか、幼稚園でレイヤを選択する項目を追加するかのどちらでしょうか。
・データがないのにPOIがつく問題は、幼稚園がまだ対応保留状態のために起こっており、すぐなおせます。

**Comment by misopeso** [comment]
> データがないのにPOIがつく問題は、幼稚園がまだ対応保留状態のために起こっており、すぐなおせます。

こちら、何が原因で待ち状態になってますか？

**Comment by snakamu** [comment]
幼稚園データがないときに、保留だっただけで、今は待ちでないです。
言葉足らずですいません。

**Comment by misopeso** [comment]
@ShigekiNakamura 「データがないのにPOIがつく問題」は、今日リリースに含められますか？ 

検索条件がどのデータに対して有効なのか、複数選択されたときの挙動などは、整理した方がよさそうですね。

**Comment by snakamu** [comment]
POI問題はローカルでは対応しておりまして、他も仕様を決めて頂ければ可能かと思います。
ただ、本日帰りが遅く23時ぐらいからの対応になりますがよろしいでしょうか。

**Comment by iMitsugu** [comment]
認可・認可外・幼稚園のレイヤ（左上ボタン）と、絞込み検索は挙動が独立したもの、というのが基本的な考えでしたので、絞りこみ検索を操作した場合（例：保育ルーム認定）を選択した場合、各レイヤのボタンは有効になった状態でPOIは表示されないという状態を保ったほうが良いと思います。

もし上記で認識があってましたら本日遅くなってからの対応でも結構です。

**Comment by snakamu** [comment]
レイヤは一律選択し、poiでデータと結びつけるですと、対応もシンプルですので、すぐに直せると思います。
帰宅後対応します。よろしくお願いします。

**Comment by iMitsugu** [comment]
よろしくお願いいたします。

**Comment by misopeso** [comment]
PR みて、いろいろ理解できました。

検索条件のところは、札幌版は「認可保育園」と「認可外保育園」に分かれて設定しているので、表示もそれに合わせていたんですね。

千葉版で検索条件を統合したときに、レイヤの制御も検討したほうがよかったようです。

**Comment by iMitsugu** [comment]
はい。そのように思います。次回もくもく会の際にでもお話ししたいと思います。
