### ISSUE TITLE
データのY,Nはそれぞれある／ないを明示する。nullの場合は項目を非表示とする。

### ISSUE THREAD

**Issue by ymits** [codeforchiba/papamama#5]
現状Yだと表示（例、空室あり）、それ以外だと非表示となっているが
Y：空室あり　N：空室なし　と「なし」の場合も表示するようにする

**Comment by seitaro1227** [comment]
比較画面は現状で対応済み
園詳細をY/N(表示)/null(非表示)にする

**Comment by seitaro1227** [comment]
(一時保育|休日保育|夜間保育|24時間)の見出しの表示を修正
見出しをthタグに移動して(あり|なし)をtdタグに表示するようにした。
