### ISSUE TITLE
先取りプロジェクト認定、保育ルーム認定のデータが無い

### ISSUE THREAD

**Issue by misopeso** [codeforchiba/papamama#53]
絞り込みをしてもデータがないので、1件もでてこない。データができるまでは、絞り込み条件から外すか、下記からデータを作った方がよい。

http://www.city.chiba.jp/kodomomirai/kodomomirai/unei/ninkagai.html

**Comment by iMitsugu** [comment]
これらの指定は千葉市側の希望だったので、確認の上結論出します。

**Comment by iMitsugu** [comment]
12/2版のデータにおいて、それぞれのデータが入りました。データ更新をお願いできますでしょうか？

**Comment by ymits** [comment]
データ更新で対応完了
