### ISSUE TITLE
「こども園」「事業所内保育所」も絞り込めるように検討する。

### ISSUE THREAD

**Issue by ymits** [codeforchiba/papamama#6]
検索条件として「こども園」「事業所内保育所」を絞り込めるようにする。
あとは園の詳細ダイアログ、園比較の画面で値をだす

**Comment by ymits** [comment]
今回Y, Nの項目についてはNの値も出す要件ですが、さすがに「認定こども園でない」「事業所内保育所でない」という情報はさすがに情報として不要だと思ったのでYの時だけ値を表示するようにしています。

問題ないですかね？

**Comment by iMitsugu** [comment]
確かにそのとおりだと思います。データ仕様としてはそのままで、表示仕様として実装していただければと思います。
