### ISSUE TITLE
比較機能で、申し込み倍率が正しく表示されない

### ISSUE THREAD

**Issue by misopeso** [codeforchiba/papamama#61]
作草部保育園で発生しました。

詳細画面では、1.17倍と表示されますが、

<img width="322" alt="_by_code_for_chiba" src="https://cloud.githubusercontent.com/assets/614339/20750748/be7d9580-b73b-11e6-9a20-8c3851ad2a46.png">

比較画面で見ると、体操服あり倍となります。

<img width="365" alt="default" src="https://cloud.githubusercontent.com/assets/614339/20750783/ec720700-b73b-11e6-9329-01d7e0b652a7.png">

**Comment by ymits** [comment]
対応済み
