### ISSUE TITLE
(スマホ)POI押下時、詳細画面上のリンク先に勝手に飛ぶ

### ISSUE THREAD

**Issue by snakamu** [codeforchiba/papamama#63]
スマホだけであるが、POI押下時に、保育所等空き状況一覧ページが勝手に開く。
詳細画面の中心付近にリンクがある施設は、POI押下時に勝手にリンク先に飛んでしまうように見える。
【検証端末】
Android: Nexus5 
iOS: iphone5s

**Comment by snakamu** [comment]
現象を見る限り、画面上に指がある状態で詳細画面が開き、詳細画面の中心のリンクを押してしまっているように思われます。
案としては、下記画像のようにリンクを項目名にもってくる(中心からずらす)と解決します。
対応については相談させてください。よろしくお願いします。

![detail_link](https://cloud.githubusercontent.com/assets/11253385/20857744/a0ee34cc-b978-11e6-8e00-bc5fef49e949.png)

**Comment by snakamu** [comment]
欠員項目を最上部にもっていく方針とする。

**Comment by misopeso** [comment]
#77 で FIX したと判断。
