### ISSUE TITLE
背景を「交通」に変更すると、地図が表示されない

### ISSUE THREAD

**Issue by misopeso** [codeforchiba/papamama#67]
Mac / Chrome です。

<img width="1226" alt="_by_code_for_chiba" src="https://cloud.githubusercontent.com/assets/614339/20970642/e398e8c4-bcd1-11e6-8ea5-83f3ea5ab5f5.png">

**Comment by snakamu** [comment]
こちら、https://github.com/codeforchiba/papamama/issues/64 と同じく、
下記対応から事象発生しております。
>502e7e3 ライブラリをCDN化

**Comment by ymits** [comment]
#67 にて対応済み
