### ISSUE TITLE
Code for Chiba が運営しているとわかるようにする

### ISSUE THREAD

**Issue by misopeso** [codeforchiba/papamama#70]
ちば保育園マップを使っている人が、千葉市の各区宛てに電話などで問い合わせしていることがわかった。

原因として、こちらのように千葉市のウェブサイトからリンクが張られているが、

http://www.city.chiba.jp/kodomomirai/kodomomirai/unei/h28goannnai.html

現在のちば保育園マップには、どこのだれが作ったのかという情報がファーストビューにないため、千葉市管理のサイトと勘違いしていると思われる。そのため、ここをわかりやすくしてあげる必要がある。

最初の対策として、？ 先を Github ではなく、ちば保育園マップとは？ がわかるページを作成し、差し替える。

**Comment by ymits** [comment]
説明ページがトップに来るように対応済みのためクローズ
