### ISSUE TITLE
先取りプロジェクト・保育ルームを表示する

### ISSUE THREAD

**Issue by ymits** [codeforchiba/papamama#74]
検索画面から消す

詳細ダイアログのタイトル1行目に記載し、２行目に園名を表示する
例)
[認可外][先取りプロジェクト][私立]
ミルキーホーム

比較画面では
認可外[先取りプロジェクト]
認可外[保育ルーム]

と表示する

※[先取りプロジェクト][保育ルーム]という名称は仮。名称は後ほど確定させる

**Comment by snakamu** [comment]
https://github.com/codeforchiba/papamama/pull/79 で対応済
