### ISSUE TITLE
認可外のうち、「先取りプロジェクト」「保育ルーム認定」を差別化したい。

### ISSUE THREAD

**Issue by ymits** [codeforchiba/papamama#8]
検索条件として絞り込めるようにして
園の詳細ダイアログと園の比較画面に値を表示するようにする

**Comment by seitaro1227** [comment]
比較画面での表示は、園が両方とも「認可外」である場合に表示するようにした。

**Comment by seitaro1227** [comment]
#4 と競合する為、developへのマージを待ってからプルリクを作成します。

**Comment by seitaro1227** [comment]
#4 の変更を取り込んだ上で再度Pushしました。
