### ISSUE TITLE
プルダウンメニュー（例：最寄駅）を指定した状態にすると、メニュー内の文字が白くなり見えなくなる（選択した項目は反転表示され読むことができる）。 「背景」や「円表示」でも同様の現象が起きる。

### ISSUE THREAD

**Issue by iMitsugu** [codeforchiba/papamama#82]
![pasted image at 2017_01_25 02_25 am](https://cloud.githubusercontent.com/assets/23208846/22350951/18e8716c-e459-11e6-97ca-4e57cb49f8c6.png)

**Comment by ymits** [comment]
こちらの環境情報を教えてもらってもいいですか？

自分のmac+chrome or mac+safari環境では再現しなかったです。

**Comment by ymits** [comment]
bootstrap内の

```
button,input,optgroup,select,textarea {
    margin: 0;
    font: inherit;
    color: inherit;
}
```

の定義の内

```
color: inherit;
```

が悪さをしていそう。

**Comment by ymits** [comment]
ちなみに札幌保育園マップ時代から事象は発生している

**Comment by ymits** [comment]
ちょっと乱暴にbootstrapのバージョンを上げてみる。。。
動かなくなるかも。。

**Comment by ymits** [comment]
ここに全く同じ問題の人が。

bootstrap + jquery mobileだと問題が発生しそうです。

http://stackoverflow.com/questions/38550705/dropdown-options-not-visible-with-jquery-mobile-and-bootstrap

**Comment by ymits** [comment]
bootstrapのバージョンあげてもこのコンフリクト問題は解決しないので強制的にスタイルを上書いちゃいます。

**Comment by snakamu** [comment]
#92 で対応済み
